// Generated by jextract

package jp.yukoba.gymnes;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$0 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$0() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.ofVoid(
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandleVariadic(
        "__va_start",
        constants$0.const$0
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "__security_init_cookie",
        constants$0.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.ofVoid(
        JAVA_LONG
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "__security_check_cookie",
        constants$0.const$4
    );
}


